export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INPUT_TEXT = 'INPUT_TEXT';
export const COMMENT_TEXT = 'COMMENT_TEXT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const COMMENTS_LOAD = 'COMMENTS_LOAD';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
